[package]
name = "elma2"
version = "0.1.0"
authors = ["kryptan"]
edition = "2018"

[dependencies]
elma = "0.1"
glutin = "0.24"
cgmath = "0.17"
lyon_tessellation = "0.15"
pcx = "0.2"
rect_packer = "0.2"
image = "0.23"

[build-dependencies]
gl_generator = "0.14"
