[package]
name = "elma2"
version = "0.1.0"
authors = ["kryptan"]

[dependencies]
elma = "0.1"
gfx = "0.12"
glutin = "0.6"
gfx_window_glutin = "0.12.0"
cgmath = "0.12"
lyon_tessellation = "0.3"
lyon_core = "0.3.2"
lyon_path_iterator = "0.3.2"
lyon_path = "0.3.2"
lyon_path_builder = "0.3.2"
